<a href="https://colab.research.google.com/github/baotam27/DeepLearning/blob/main/Tuan1_Lab1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Tạo array 1 chiều

In [2]:
#cách 1
#tạo list
my_list = [1,9,15,39]
print('Python list:',my_list)

#chuyển list --Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:',my_numpy_array)

#cách 2
a = np.array([1,9,15,39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


Tạo Array 2 chiều


In [3]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


Tạo Array 3 chiều

In [4]:
d = np.array([
    [[1.,2.,3.],[4.,5.,6.]],
    [[7.,8.,9.],[10,11,12]]
    ])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


Tạo Array với giá trị ban đầu là 0 hoặc 1

In [5]:
e = np.zeros((2,2))
f = np.ones((3,3))
print('Zero matrix: \n',e)
print('One matrix\n',f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Reshape thay đổi kích thước ma trận


In [6]:
e=np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f=e.reshape(3,2)
print(f)
g = np.array([
    [[1.,2.,3.],[4.,5.,6.]],
    [[7.,8.,9.],[10,11,12]]
    ])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape (3,4)\n',h)
j=g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k=g.reshape(2,3,2)
print('reshape (2,3,2)\n',k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


Platten là chuyển array nhiều chiều về 1 chiều


In [7]:
e=np.array([[1.,2.,3.],[4.,5.,6.]])
f=e.flatten()
print(f)
g = np.array([
    [[1.,2.,3.],[4.,5.,6.]],
    [[7.,8.,9.],[10,11,12]]
    ])
j=g.flatten()
print(j)


[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


3.6. Thêm dòng dữ liệu với hstack và vstack

In [8]:
f = np.array([1.,2.,3.])
g = np.array([4.,5.,6.])
h_stack = np.hstack((f,g))
print('Horizontal Append\n',h_stack)
v_stack = np.vstack((f,g))
print('Vertical Append\n',v_stack)


Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


3.7. Sinh mảng số ngẫu nhiên

In [10]:
a=np.random.randint(100, size=(5,))
print('random 1-D array\n',a)
b=np.random.randint(100, size=(3, 4))
print('random 2-D array\n',b)
c=np.random.randint(100, size=(3, 4, 3))
print('random 1-D array\n',c)


random 1-D array
 [43 75 54 13 59]
random 2-D array
 [[36 34 65 21]
 [65 36 97  0]
 [78 36 37 46]]
random 1-D array
 [[[64 18 25]
  [52 12 84]
  [10 57 99]
  [44  4 96]]

 [[35 21 72]
  [42 68 10]
  [72 68 24]
  [10 33 63]]

 [[97 76 92]
  [62 13 64]
  [ 4 28 77]
  [34 73 80]]]


3.7.2 Sinh mảng số thực trong khoảng [0,1]

In [12]:
#sinh ngẫu nhiên mảng số thực [0,1]
a=np.random.rand(5)
print('Random 1-D array\n',a)
b=np.random.rand(3,4)
print('Random 2-D array\n',b)
c=np.random.rand(3,4,3)
print('Random 3-D array\n',c)

Random 1-D array
 [0.99641539 0.1358625  0.40297769 0.73752795 0.18669117]
Random 2-D array
 [[0.58960365 0.32174451 0.40303454 0.75900977]
 [0.7297277  0.89493331 0.12861298 0.19825915]
 [0.88757288 0.44500683 0.65286336 0.31888785]]
Random 3-D array
 [[[0.71483987 0.76288485 0.70390145]
  [0.68331124 0.8877107  0.88855937]
  [0.63633066 0.43674844 0.20352391]
  [0.19922722 0.39077069 0.33971147]]

 [[0.05514106 0.23191417 0.22739358]
  [0.330349   0.69499945 0.28824228]
  [0.93697369 0.98518469 0.42609029]
  [0.36188345 0.60371196 0.73358794]]

 [[0.19477268 0.07803008 0.57296417]
  [0.27917422 0.06945094 0.47796919]
  [0.34916951 0.97214071 0.37766506]
  [0.19506204 0.65513468 0.61674723]]]


BÀI TẬP

1. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tất cả các phần tử trong mảng khác 0

In [13]:
# Tao mang 3x3 gom cac so nguyen ngau nhien tu 0 den 20
arr_1 = np.random.randint(0, 21, size=(3, 3))
print("Mảng 3x3:\n", arr_1)

# Kiem tra xem tat ca cac phan tu co khac 0 hay khong
check_all = np.all(arr_1 != 0)
print("Tất cả phần tử khác 0:", check_all)

Mảng 3x3:
 [[13  5  1]
 [ 8 17 14]
 [ 5  1  4]]
Tất cả phần tử khác 0: True


2. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tồn tại một phần tử trong mảng khác 0

In [14]:
# Tao mang 3x3 gom cac so nguyen ngau nhien tu 0 den 20
arr_2 = np.random.randint(0, 21, size=(3, 3))
print("Mảng 3x3:\n", arr_2)

# Kiem tra xem co it nhat mot phan tu khac 0 hay khong
check_any = np.any(arr_2 != 0)
print("Có tồn tại phần tử khác 0:", check_any)

Mảng 3x3:
 [[ 2  6 18]
 [20  2 12]
 [ 7 12  3]]
Có tồn tại phần tử khác 0: True


3. Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater,
numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.

In [15]:
# Khoi tao mang 1 chieu va 2 chieu
arr1d_a = np.array([5, 10, 15])
arr1d_b = np.array([5, 8, 20])
arr2d_a = np.array([[1, 6], [8, 4]])
arr2d_b = np.array([[3, 6], [7, 5]])

# So sanh mang 1 chieu
print("Mảng 1D lớn hơn (greater):\n", np.greater(arr1d_a, arr1d_b))
print("Mảng 1D lớn hơn hoặc bằng (greater_equal):\n", np.greater_equal(arr1d_a, arr1d_b))

# So sanh mang 2 chieu
print("Mảng 2D nhỏ hơn (less):\n", np.less(arr2d_a, arr2d_b))
print("Mảng 2D nhỏ hơn hoặc bằng (less_equal):\n", np.less_equal(arr2d_a, arr2d_b))

Mảng 1D lớn hơn (greater):
 [False  True False]
Mảng 1D lớn hơn hoặc bằng (greater_equal):
 [ True  True False]
Mảng 2D nhỏ hơn (less):
 [[ True False]
 [False  True]]
Mảng 2D nhỏ hơn hoặc bằng (less_equal):
 [[ True  True]
 [False  True]]


4. Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5

In [16]:
# Tao tung mang con voi so luong yeu cau
arr_ones = np.ones(10, dtype=int)
arr_zeros = np.zeros(10, dtype=int)
arr_fives = np.full(10, 5, dtype=int)

# Ghep cac mang lai voi nhau
arr_combined = np.concatenate((arr_ones, arr_zeros, arr_fives))
print("Mảng kết hợp:\n", arr_combined)

Mảng kết hợp:
 [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]
