<a href="https://colab.research.google.com/github/baotam27/DeepLearning/blob/main/Tuan1_Lab1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSORRFLOW

In [ ]:
import tensorflow as tf
import numpy as np

3.1 Tensor 0 chiều

In [ ]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, tf.int16)
print(r1)
r1_float=tf.constant(1.12, tf.float32)
print(r1_float)
r1_string = tf.constant('hello', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'hello', shape=(), dtype=string)


3.2 Tensor 1 chiều

In [ ]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)


tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


3.3 Tensor 2 chiều (ma trận)

In [ ]:
rank_2_tensor=tf.constant([[1,2],
                           [3,4],
                           [5,6]],dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


3.4 Tensor n chiều (nhiều trục)

In [ ]:
rank_3_tensor=tf.constant([
    [[0,1,2,3,4],
     [5,6,7,8,9]],
     [[10,11,12,13,14],
     [15,16,17,18,19]],
     [[20,21,22,23,24],
      [25,26,27,28,29]],])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


3.5 Thuộc tính của Tensor

In [ ]:
rank_3_tensor=tf.constant([
    [[0,1,2,3,4],
     [5,6,7,8,9]],
     [[10,11,12,13,14],
     [15,16,17,18,19]],
     [[20,21,22,23,24],
      [25,26,27,28,29]],])
print(rank_3_tensor)
print('shape: ',rank_3_tensor.shape)
print('type of tensor: ',rank_3_tensor.dtype)


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape:  (3, 2, 5)
type of tensor:  <dtype: 'int32'>


3.6 Tạo Tensor tự động gán giá trị 0 ban đầu

In [ ]:
t_zero=tf.zeros(10)
print(t_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [ ]:
t_2_zero=tf.zeros([3,3])
print(t_2_zero)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
t_3_zero=tf.zeros([3,3,5])
print(t_3_zero)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


3.7 Tạo tensor tự động gán giá trị 1 ban đầu

In [ ]:
t_one=tf.ones(10)
print(t_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)


In [ ]:
t_2_one=tf.ones([3,3])
print(t_2_one)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
t_3_one=tf.ones([3,3,5])
print(t_3_one)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


3.8 Tạo Tensor tự động với giá trị bất kỳ

In [ ]:
t_1=tf.fill(3,10)
print(t_1)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [ ]:
t_2=tf.fill([3,3],9)
print(t_2)

tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


3.9 Tạo tensor 1 chiều với hàm linspace

In [ ]:
lin_tensor=tf.linspace(5.0,20.0,5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


3.10 Tạo tensor 1 chiều với hàm Range

In [ ]:
range_tensor=tf.range(3.0,7.0,delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


In [ ]:
range_tensor=tf.range(3.0,delta=0.5)
print(range_tensor)

tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


3.11 Tạo Tensor với giá trị ngẫu nhiên

In [ ]:
range_tensor=tf.random.normal([5])
print(range_tensor)

tf.Tensor([ 0.49713707  0.57984006 -0.67815286 -0.849389    0.6867145 ], shape=(5,), dtype=float32)


In [ ]:
range_tensor=tf.random.normal([3,3])
print(range_tensor)

tf.Tensor(
[[-0.32735234 -1.3598127   0.9451816 ]
 [ 0.45092055  0.88115907 -0.86276656]
 [-0.8553602   0.20085742 -1.0168334 ]], shape=(3, 3), dtype=float32)


3.12 Chuyển đổi kiểu dữ liệu

In [ ]:
t_float=tf.constant(3.9,tf.float32)
print(t_float,'---',t_float.dtype)
t_int=tf.cast(t_float,tf.int32)
print(t_int,'---',t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


3.13 Các phép toán trong tensorflow

3.13.1 Tính căn bậc 2 của một tensor scalar

In [24]:
x = tf.constant(2, dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)
